### ISSUE TITLE
How can I to enter admin page?

### ISSUE THREAD

**Issue by wisehouse** [dnd-al-krk/portal#1]
I installed portAL on ubuntu 18.4,
cloned those three repository,
configured,
docker-compose up,
and installed nginx as proxy.

nginx:80/api => backend:8000/api
nginx:80/ => frontend:3000/

where is admin page?
I tried at backend:8000/admin, but got a message as template not found

I am working with @lovehoonie.

**Comment by wisehouse** [comment]
I got your message via @lovehoonie.

This issue is resolved.
Thanks.

**Comment by ivellios** [comment]
To clarify for the future - admin is available under /admin/ (trailing slash is important!)
